### ISSUE TITLE
Default values that use nested enums fail with NameError

### ISSUE THREAD

**Issue by schmichael** [bumptech/palm#8]
_t.proto_

```
message M {
    optional Options opt = 1 [default = NONE];

    enum Options {
        NONE = 0;
        NOT_NONE = 1;
    }
}
```

``` shell
palmc . .
python
```

``` python

>>> import t_palm
>>> t_palm.M(t_palm.M().dumps()).opt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "t_palm.py", line 51, in _get_opt
    r = NONE
NameError: global name 'NONE' is not defined
```

Setting `default = M.NONE` or `default = Options.NONE` are both invalid.

**Comment by wadey** [comment]
Same bug happens with nested `message`s.

**Comment by dowski** [comment]
I am able to repro this issue.

**Comment by dowski** [comment]
@wadey Do you think you could try the code in the pull request and see if it fixes your issue? It targets the specific issue @schmichael mentioned but maybe covers yours as well?

**Comment by dowski** [comment]
No activity for a while, and we put in a fix, so I'm going to close this.
